name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Log in to Docker Hub using your access token
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  # Use the access token here

    # Build the Docker image
    - name: Build the Docker image
      run: docker build ./public_html --file ./public_html/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/netcommand:$(date +%s)

    # Push the Docker image to your private Docker Hub repository
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/netcommand:$(date +%s)
