name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Build the Docker image
    - name: Build the Docker image
      run: docker build ./public_html --file ./public_html/Dockerfile --tag netcommand:$(date +%s)

    # Save the Docker image as a tarball
    - name: Save Docker image as tarball
      run: docker save netcommand:$(date +%s) | gzip > netcommand_image.tar.gz

    # Upload the image as an artifact
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: netcommand_image.tar.gz
